### ISSUE TITLE
App not working after the upgrade to iOS 14.3

### ISSUE THREAD

**Issue by zero0ID** [kkk669/DNSecure#29] opened 2021-01-03 10:05 UTC
It's not working with the initially delivered server configs nor with newly added.
The DNS setting was activated as requested.

![F0267413-3EF9-44C1-8DA9-413CC290B0D0](https://user-images.githubusercontent.com/76554148/103476158-89b8b380-4db3-11eb-9633-21fa9757ee58.png)

**Comment by kkk669** [comment] 2021-01-05 17:05
@zero0ID Thank you for reporting. I've confirmed that the problem is reproduced. I'll investigate it.

As a workaround for a while, please try the following steps.

1. Open the DNSecure app
2. Select a server from the sidebar
3. Enable "Use This Server"
4. Open the Settings app
5. Go to "VPN & Network" settings
6. Select "DNSecure" for "DNS" settings
7. **[Force quit the DNSecure app](https://support.apple.com/en-us/HT201330)** without opening it
8. Re-open the DNSecure app

**Comment by zero0ID** [comment] 2021-01-06 17:50
Hi kkk669,
seems that the emergency solution works. Strange are the DoT test results for this server (https://blog.uncensoreddns.org/blog/) on https://rootcanary.org/test.html
Usually there I get unlocked only for the GOST line and ECC GOST column.

![328EE78A-6381-4C1E-A03D-F76648E6101E](https://user-images.githubusercontent.com/76554148/103802781-f2bc5780-504f-11eb-88d4-e5e805d557da.jpeg)

**Comment by kkk669** [comment] 2021-01-06 18:08
Thank you @zero0ID.

> Strange are the DoT test results for this server

The result seems to change every time I re-run test, so I'm not sure whether the test is unstable or Apple's DoT implementation is unstable.

**Comment by zero0ID** [comment] 2021-01-07 09:58
Maybe you have an address where to check the DoT and DoH configuration please?

**Comment by kkk669** [comment] 2021-01-07 14:21
@zero0ID I usually verify a DNS-over-TLS/HTTPS connection by capturing packets with Wireshark or Charles.

Also, you can use another DNS leak test [described in the LibreOps blog](https://libreops.cc/2020/10/14/libredns-ios/).

**Comment by kkk669** [comment] 2021-01-07 14:31
Closed by #30

**Closed by kkk669** 2021-01-07 14:31 UTC
Labels: bug
